# Generated by Django 5.0 on 2023-12-20 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrollModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='scroll')),
                ('discount', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=50)),
                ('creat_at', models.DateTimeField()),
                ('update_at', models.DateTimeField()),
            ],
        ),
    ]
