# Generated by Django 5.0 on 2023-12-20 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scrollmodel',
            options={'verbose_name': 'scroll', 'verbose_name_plural': 'scrolls'},
        ),
    ]
