# Generated by Django 5.0 on 2023-12-20 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_scrollmodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrollmodel',
            name='desctription',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='scrollmodel',
            name='creat_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='scrollmodel',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
