# Generated by Django 5.0 on 2023-12-21 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_imagemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='BurgerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='burger')),
                ('title', models.CharField(max_length=50)),
                ('desctription', models.TextField()),
                ('price', models.FloatField()),
                ('creat_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'burger',
                'verbose_name_plural': 'burgers',
            },
        ),
        migrations.CreateModel(
            name='DrinksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='drinks')),
                ('title', models.CharField(max_length=50)),
                ('desctription', models.TextField()),
                ('price', models.FloatField()),
                ('creat_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'drinks',
                'verbose_name_plural': 'drinks',
            },
        ),
        migrations.CreateModel(
            name='FricesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='frices')),
                ('title', models.CharField(max_length=50)),
                ('desctription', models.TextField()),
                ('price', models.FloatField()),
                ('creat_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'frices',
                'verbose_name_plural': 'frices',
            },
        ),
        migrations.CreateModel(
            name='PizzaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pizza')),
                ('title', models.CharField(max_length=50)),
                ('desctription', models.TextField()),
                ('price', models.FloatField()),
                ('creat_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'pizza',
                'verbose_name_plural': 'pizzas',
            },
        ),
        migrations.CreateModel(
            name='SaladModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='salad')),
                ('title', models.CharField(max_length=50)),
                ('desctription', models.TextField()),
                ('price', models.FloatField()),
                ('creat_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'salad',
                'verbose_name_plural': 'salads',
            },
        ),
        migrations.AlterModelOptions(
            name='imagemodel',
            options={'verbose_name': 'image', 'verbose_name_plural': 'images'},
        ),
    ]
