# Generated by Django 5.0 on 2023-12-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_burgermodel_drinksmodel_fricesmodel_pizzamodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=15)),
                ('time', models.CharField(max_length=10)),
                ('message', models.TextField()),
            ],
        ),
    ]
